version: "3"

services:
  postgres:
    container_name: gqlnuberpg
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gqlnuberpg_db
      POSTGRES_PORT: 5432
    volumes:
    - /data/gqlnuberpg:/data/postgres
    networks:
    - pgnuber

  pgadmin:
    links:
    - postgres:postgres
    container_name: pgnuberadmin
    image: dpage/pgadmin4:latest
    ports:
    - "8080:80"
    volumes:
    - /data/pgnuberadmin:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
    - pgnuber

networks:
  pgnuber:
    driver: bridge